### ISSUE TITLE
coach pull doesn't work with tagged images

### ISSUE THREAD

**Issue by aleksijohansson** [james-nesbitt/coach#13]
Please see screenshot :https://goo.gl/photos/Q72wymvanjV4B1nr8

Go 1.4.2
Docker 1.8.0-rc3 (tried also 1.7.0)

**Comment by james-nesbitt** [comment]
I will take a look at this today

**Comment by james-nesbitt** [comment]
@aleksijohansson is this with your github.com/aleksijohansson/docker-drupal-coach nodes.yml?  If not, can you give a access to your nodes.yml?

**Comment by james-nesbitt** [comment]
never mind. I found it.

**Comment by james-nesbitt** [comment]
I think that PR 15 fixes this https://github.com/james-nesbitt/coach/pull/15

**Comment by james-nesbitt** [comment]
tested on Fedora

```
    [james@sd-60942 aleksi]$ coach pull
    (5)[OPERATION][PULL]--------    running pull operation
    (5)[NODES][NODE:memcache]---    PULLING NODE IMAGE [memcache] FROM SERVER [https://index.docker.io/v1/] USING AUTH [] : memcached:1.4.24
    Pulling from docker.io/memcached
    Already exists
    Already exists
    Already exists
    Already exists
    Already exists
    Already exists
    Already exists
    Already exists
    Already exists
    Already exists
    Digest: sha256:3802d37d06ce55b8fbff795f8f00cb9781e8239ec6de53610c4caf21f31ac1a7
    Status: Image is up to date for docker.io/memcached:1.4.24
```

**Comment by aleksijohansson** [comment]
Tested on Fedora, RancherOS and CoreOS and seems to be working really good now!

Whole workflow:

coach init git https://github.com/aleksijohansson/docker-drupal-coach
./prepare.sh (template specific)
coach pull
coach build
coach create
coach start
coach stop
coach remove
coach destroy

Fedora 22:

Go:
go version go1.4.2 linux/amd64

Docker:

Client:
Version:      1.8.1
API version:  1.20
Go version:   go1.4.2
Git commit:   d12ea79
Built:        Thu Aug 13 02:39:27 UTC 2015
OS/Arch:      linux/amd64

Server:
Version:      1.8.1
API version:  1.20
Go version:   go1.4.2
Git commit:   d12ea79
Built:        Thu Aug 13 02:39:27 UTC 2015
OS/Arch:      linux/amd64

RancherOS:
rancherctl version v0.3.3

Go:
go version go1.4.2 linux/amd64

Docker:
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 851c91a
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 851c91a
OS/Arch (server): linux/amd64

CoreOS:
CoreOS alpha (774.0.0)

Go:
go version go1.4.2 linux/amd64

Docker:
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 2c2c52b-dirty
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 2c2c52b-dirty
OS/Arch (server): linux/amd64
