### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by aleksijohansson** [james-nesbitt/coach#19]
For example, what is the new run command for and how to use it?

**Comment by james-nesbitt** [comment]
definitely could use some work.

Should I attach this issue to the 0.2 milestone?

Here are some ideas that I have:
1. improve inline commenting  (low priority)
2. improve wiki with base conf layout, conf files, & per operation pages
3. implement help operation, so that "$/> coach help run" gives instructions for the run operation.

**Comment by james-nesbitt** [comment]
The run operation is being re-written to allow for persistant command containers.  I will finish this task first, before implementing a help operation.

**Comment by james-nesbitt** [comment]
I am working on a "help" operation now.  It should be available in a basic form in a day or two.

**Comment by james-nesbitt** [comment]
https://github.com/james-nesbitt/coach/pull/22 adds a new help feature.

The current help info is not much to look at, but it includes a new help framework which should make it easy to provide abstracted help.

**Comment by james-nesbitt** [comment]
The run help offers a bit more insight into how it works now.

**Comment by james-nesbitt** [comment]
This issue is the last blocker for https://github.com/james-nesbitt/coach/milestones/0.2

**Comment by james-nesbitt** [comment]
this issue was moved to milestone 0.3 so that 0.2 could be closed.

**Comment by james-nesbitt** [comment]
I am currently working on the wiki and the README.  After this I will move on to fleshing out the help output:
- the help operation should itself recognize certain topics such as "nodes.yml", "targets", "tokens"
- all operations should have better help topics.

WIKI: https://github.com/james-nesbitt/coach/wiki

**Comment by james-nesbitt** [comment]
closing this issue after a short discussion with A.J.
