### ISSUE TITLE
coach init git hangs

### ISSUE THREAD

**Issue by aleksijohansson** [james-nesbitt/coach#8]
Running coach init git hangs. Tested with:

coach init git https://github.com/aleksijohansson/docker-drupal-coach

Tested on:

Fedora 22, Docker 1.8.0-rc2
RancherOS, Docker 1.7.1
CoreOS, Docker 1.6.2

**Comment by james-nesbitt** [comment]
Can you give me an idea of how long you waited for it to work.  On my system, it looks like it hangs, but then downloads properly.

**Comment by james-nesbitt** [comment]
On a side note, I should fix the os.exec, so that the tty output is displayed.

**Comment by james-nesbitt** [comment]
I am looking into this now.

**Comment by james-nesbitt** [comment]
strange:

```
    james@akaryuu [11:24:42] [~/Documents/Develop/coach] 
    -> % mkdir aleksi-docker-coach

    james@akaryuu [11:24:53] [~/Documents/Develop/coach] 
    -> % cd aleksi-docker-coach 

    james@akaryuu [11:24:55] [~/Documents/Develop/coach/aleksi-docker-coach] 
    -> % coach init git https://github.com/aleksijohansson/docker-drupal-coach
    (6)[CONF][DEFAULT]----------    Could not find a project folder, coach will assume that this project is not initialized.
    (6)[CONF]-------------------    This project contains no CONF Yaml file
    (6)[NODES][YAML]------------    Could not read the YAML file: open /home/james/.coach/nodes.yml: no such file or directory
    (5)[OPERATION][INIT]--------    Preparing INIT operation in path : /home/james/Documents/Develop/coach/aleksi-docker-coach
    (5)[OPERATION][INIT][GIT]---    Clone remote repository to local project folder [https://github.com/aleksijohansson/docker-drupal-coach]
    (5)[OPERATION][INIT][GIT]---    Cloned remote repository to local project folder
    (5)[OPERATION][INIT][GIT]---    --> Create file : .coach/CREATEDFROM.md

    james@akaryuu [11:25:04] [~/Documents/Develop/coach/aleksi-docker-coach] [master *]
    -> % ls -la
    total 64
    drwxr-xr-x 1 james james   270 Aug  9 11:25 .
    drwxr-xr-x 1 james james   124 Aug  9 11:24 ..
    -rwxr-xr-x 1 james james  1287 Aug  9 11:25 bash.sh
    -rwxr-xr-x 1 james james  1336 Aug  9 11:25 build.sh
    drwxr-xr-x 1 james james    88 Aug  9 11:25 .coach
    drwxr-xr-x 1 james james    30 Aug  9 11:25 conf
    drwxr-xr-x 1 james james   216 Aug  9 11:25 docs
    drwxr-xr-x 1 james james   100 Aug  9 11:25 drupal
    -rwxr-xr-x 1 james james  1275 Aug  9 11:25 drush.sh
    drwxr-xr-x 1 james james   138 Aug  9 11:25 .git
    -rw-r--r-- 1 james james   306 Aug  9 11:25 .gitignore
    -rwxr-xr-x 1 james james  2127 Aug  9 11:25 helper.sh
    -rw-r--r-- 1 james james 18047 Aug  9 11:25 LICENSE
    -rwxr-xr-x 1 james james   662 Aug  9 11:25 parse_yaml.sh
    -rwxr-xr-x 1 james james   557 Aug  9 11:25 prepare.sh
    -rw-r--r-- 1 james james  1687 Aug  9 11:25 README.md
    -rwxr-xr-x 1 james james  4142 Aug  9 11:25 update_environment.sh
    -rwxr-xr-x 1 james james   229 Aug  9 11:25 update.sh
```

**Comment by james-nesbitt** [comment]
is there any chance that it's waiting for an RSA passphrase?

**Comment by james-nesbitt** [comment]
@aleksijohansson pls check out this PR: https://github.com/james-nesbitt/coach/pull/11
- git clone stdout&stderr are connected (more verbose)
- stdin is connected in case you need to enter a passphrase
- git clone has --progress flag added

**Comment by aleksijohansson** [comment]
I'll test this now.

**Comment by james-nesbitt** [comment]
Here is some example output from my terminal:

```
    james@akaryuu [02:55:57] [~/Documents/Develop/coach/aleksi-docker-coach] 
    -> % coach init git git://github.com/aleksijohansson/docker-drupal-coach
    (6)[CONF][DEFAULT]----------    Could not find a project folder, coach will assume that this project is not initialized.
    (6)[CONF]-------------------    This project contains no CONF Yaml file
    (6)[NODES][YAML]------------    Could not read the YAML file: open /home/james/.coach/nodes.yml: no such file or directory
    (5)[OPERATION][INIT]--------    Preparing INIT operation in path : /home/james/Documents/Develop/coach/aleksi-docker-coach
    (5)[OPERATION][INIT][GIT]---    Clone remote repository to local project folder [git://github.com/aleksijohansson/docker-drupal-coach]
    Cloning into '/home/james/Documents/Develop/coach/aleksi-docker-coach'...
    remote: Counting objects: 570, done.        
    remote: Compressing objects: 100% (448/448), done.        
    remote: Total 570 (delta 113), reused 531 (delta 74), pack-reused 0        
    Receiving objects: 100% (570/570), 1.21 MiB | 817.00 KiB/s, done.
    Resolving deltas: 100% (113/113), done.
    Checking connectivity... done.
    (5)[OPERATION][INIT][GIT]---    Cloned remote repository to local project folder
    (5)[OPERATION][INIT][GIT]---    --> Create file : .coach/CREATEDFROM.md
```

I also tested it using a different git source, which needed a passphrase.  I was able to enter a passphrase.

**Comment by aleksijohansson** [comment]
Still nothing. Just waits for maybe 3 minutes and quits eventually. See this screenshot from RancherOS of the whole process https://goo.gl/photos/gNB7gWZ52n2ERsA9A showing also that git clone works

**Comment by james-nesbitt** [comment]
can you do it with --debug ?

**Comment by aleksijohansson** [comment]
Same result with --debug, nothing. Could there be some software dependency missing?

**Comment by james-nesbitt** [comment]
no dependency is used here that is not used in other operations, except the core golang os.exec library.

As there is no output after the exec command, golang must be hanging.  The only other option that I have is to tell go to run the command in the background and ignore it, in which case I cannot verify that the git has completed or failed.

For now you will have to try to debug the issue on your own, or wait for me to find my fedora system.

1 last question: what go version are you using?

**Comment by aleksijohansson** [comment]
Go version 1.4.2. Tried also in Ubuntu 14.04, doesn't work there either.

**Comment by james-nesbitt** [comment]
Finally, on Fedora 22, I found an infinite loop, and patched for it:

```
    [james@sd-60942 aleksi]$ coach init git https://github.com/aleksijohansson/docker-drupal-coach
    DIRECTORY SEARCH (DEFAULT): /home/james/aleksi
    (6)[CONF][DEFAULT]----------    Could not find a project folder, coach will assume that this project is not initialized.
    (6)[CONF]-------------------    This project contains no CONF Yaml file
    (6)[NODES][YAML]------------    Could not read the YAML file: open /home/james/.coach/nodes.yml: no such file or directory
    (5)[OPERATION][INIT]--------    Preparing INIT operation in path : /home/james/aleksi
    (5)[OPERATION][INIT][GIT]---    Clone remote repository to local project folder [https://github.com/aleksijohansson/docker-drupal-coach]
    Cloning into '/home/james/aleksi'...
    remote: Counting objects: 579, done.        
    remote: Total 579 (delta 0), reused 0 (delta 0), pack-reused 579        
    Receiving objects: 100% (579/579), 1.21 MiB | 0 bytes/s, done.
    Resolving deltas: 100% (115/115), done.
    Checking connectivity... done.
    (5)[OPERATION][INIT][GIT]---    Cloned remote repository to local project folder
    (5)[OPERATION][INIT][GIT]---    --> Create file : .coach/CREATEDFROM.md
```

**Comment by aleksijohansson** [comment]
Tested on Fedora, RancherOS and CoreOS and seems to be working really good now!

Whole workflow:

coach init git https://github.com/aleksijohansson/docker-drupal-coach
./prepare.sh (template specific)
coach pull
coach build
coach create
coach start
coach stop
coach remove
coach destroy

Fedora 22:

Go:
go version go1.4.2 linux/amd64

Docker:

Client:
Version:      1.8.1
API version:  1.20
Go version:   go1.4.2
Git commit:   d12ea79
Built:        Thu Aug 13 02:39:27 UTC 2015
OS/Arch:      linux/amd64

Server:
Version:      1.8.1
API version:  1.20
Go version:   go1.4.2
Git commit:   d12ea79
Built:        Thu Aug 13 02:39:27 UTC 2015
OS/Arch:      linux/amd64

RancherOS:
rancherctl version v0.3.3

Go:
go version go1.4.2 linux/amd64

Docker:
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 851c91a
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 851c91a
OS/Arch (server): linux/amd64

CoreOS:
CoreOS alpha (774.0.0)

Go:
go version go1.4.2 linux/amd64

Docker:
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 2c2c52b-dirty
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 2c2c52b-dirty
OS/Arch (server): linux/amd64
